### Tiny data for tests only
tiny_example1:
    data_root: ../../../data/
    data_format: h5
    train_data: ../../../data/tiny_example1/train.h5
    valid_data: ../../../data/tiny_example1/valid.h5
    test_data: ../../../data/tiny_example1/test.h5

