### Tiny data for tests only
tiny_example1:
    data_root: ../../../data/
    data_format: h5
    train_data: ../../../data/tiny_example1/train.h5
    valid_data: ../../../data/tiny_example1/valid.h5
    test_data: ../../../data/tiny_example1/test.h5

### Avazu
avazu_x4:
    data_root: ../../../data/
    data_format: csv
    train_data: ../../../data/avazu_x4/train.csv
    valid_data: ../../../data/avazu_x4/valid.csv
    test_data: ../../../data/avazu_x4/test.csv
    feature_cols:
        - { name: [ hour ],
          active: True, dtype: str, type: categorical, preprocess: convert_hour,fill_na: "" }
        - { name: [id,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,device_ip,device_model,device_type,device_conn_type],
          active: True, dtype: str, type: categorical, fill_na: "" }
        - { name: [ C1,C14,C15,C16,C17,C18,C19,C20,C21],
            active: True, dtype: str, type: categorical, fill_na: "" }
    label_col: { name: click, dtype: float }
    spe_processor: avazu

criteo_x4:
    data_root: ../../../data/
    data_format: csv
    train_data: ../../../data/criteo_x4/train.csv
    valid_data: ../../../data/criteo_x4/valid.csv
    test_data: ../../../data/criteo_x4/test.csv
    min_categr_count: 2
    feature_cols:
        - { name: [ I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13 ],
            active: True, dtype: float, type: categorical, preprocess: convert_to_bucket, fill_na: 0 }
        - { name: [ C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26 ],
            active: True, dtype: str, type: categorical, fill_na: "" }
    label_col: { name: Label, dtype: float }
    spe_processor: criteo