Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DCN_test:
    model: DCN
    dataset_id: tiny_example1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    crossing_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DCN_default: # This is a config template, related to feature map
    model: DCN
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 32
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 50
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DCN_avazu:
    model: DCN
    dataset_id: avazu_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512, 256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 50
    shuffle: True
    seed: 20222023
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_gauss_avazu:
    model: DCN
    dataset_id: avazu_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512, 256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 50
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_full_avazu:
    model: DCN
    dataset_id: avazu_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512, 256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 50
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_autofield_avazu: # strict to the config of AutoField
    model: DCN
    dataset_id: avazu_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-4
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512, 256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0.2
    batch_norm: False
    epochs: 50
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_avazu_x4_002_67f219f8:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 3
    dataset_id: avazu_x4
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3

DCN_mvfs_avazu:
    model: DCN
    dataset_id: avazu_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 3.0e-4
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    dnn_hidden_units: [ 1024, 512, 256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 50
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_avazu_x4_008_94ed77b8:
#    batch_norm: true
    batch_size: 10000
    crossing_layers: 3
    dataset_id: avazu_x4
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    embedding_dim: 32
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    seed: 20222023
    shuffle: true
    task: binary_classification

DCN_mvfs_avazu_x4_008_94ed77b8:
    batch_norm: true
    batch_size: 10000
    crossing_layers: 3
    dataset_id: avazu_x4
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    embedding_dim: 32
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    seed: 20222023
    shuffle: true
    task: binary_classification

DCN_mvfs2_avazu:
    model: DCN
    dataset_id: avazu_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512, 256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 50
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_gauss_iflychu:
    model: DCN
    dataset_id: ifly_chu
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192  # 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 10
    shuffle: True
    seed: 20222023
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_gauss_frappe:
    model: DCN
    dataset_id: frappe_x1
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192  # 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 9999 # 20222023 is great, 9999 is perfect
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_criteo:
    model: DCN
    dataset_id: criteo_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512, 256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 10
    shuffle: True
    seed: 20222023
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_iflychu:
    model: DCN
    dataset_id: ifly_chu
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192  # 10000
    embedding_dim: 32
    dnn_hidden_units: [1024, 512,256]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 10
    shuffle: True
    seed: 20222023
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

#DCN_gauss_iflychu:
#    model: DCN
#    dataset_id: ifly_chu
#    loss: 'binary_crossentropy'
#    metrics: [ 'logloss', 'AUC' ]
#    task: binary_classification
#    optimizer: adam
#    learning_rate: 1.0e-3
#    embedding_regularizer: 0
#    net_regularizer: 0
#    batch_size: 8192  # 10000
#    embedding_dim: 32
#    dnn_hidden_units: [1024, 512,256]
#    dnn_activations: relu
#    num_cross_layers: 3
#    net_dropout: 0
#    batch_norm: False
#    epochs: 10
#    shuffle: True
#    seed: 20222023
#    monitor: { 'AUC': 1, 'logloss': -1 }
#    monitor_mode: 'max'

DCN_iflyfu:
    model: DCN
    dataset_id: ifly_fu
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192  # 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 10
    shuffle: True
    seed: 20222023
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_frappe:
    model: DCN
    dataset_id: frappe_x1
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192  # 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 10
    shuffle: True
    seed: 20222023
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_feat_frappe:
    model: DCN
    dataset_id: frappe_x1
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 8
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    autofeat_mode: 'table'
    score_mode: 'sum_abs'
    baseline: 'mean'
    need_pretrain: False

DCN_feat_retrain_frappe:
    model: DCN
    dataset_id: frappe_x1
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 8
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    autofeat_mode: 'retrain'
    need_pretrain: True
    keep_ratio: 1
    score_version: 12


DCN_feat_avazu:
    model: DCN
    dataset_id: avazu_x4 # dont forget to change the dataset_id
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 8
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    autofeat_mode: 'table'
    need_pretrain: False
    score_mode: 'abs'
    baseline: 'zero'

DCN_feat_retrain_avazu:
    model: DCN
    dataset_id: avazu_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 8
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    autofeat_mode: 'retrain'
    need_pretrain: True
    keep_ratio: 0.1
    score_version: 1

DCN_feat_criteo:
    model: DCN
    dataset_id: criteo_x4 # dont forget to change the dataset_id
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 8
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    autofeat_mode: 'table'
    need_pretrain: False
    score_mode: 'abs'
    baseline: 'mean'

DCN_feat_retrain_criteo:
    model: DCN
    dataset_id: criteo_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 8
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    autofeat_mode: 'retrain'
    need_pretrain: True
    keep_ratio: 0.8
    score_version: 1

DCN_feat_aliccp:
    model: DCN
    dataset_id: aliccp_x4 # dont forget to change the dataset_id
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 8
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    autofeat_mode: 'table'
    need_pretrain: False
    score_mode: 'abs'
    baseline: 'mean'

DCN_feat_retrain_aliccp:
    model: DCN
    dataset_id: aliccp_x4
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 8
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    autofeat_mode: 'retrain'
    need_pretrain: True
    keep_ratio: 0.4
    score_version: ""

DCN_movielens:
    model: DCN
    dataset_id: movielens
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 10
    shuffle: True
    seed: 20222023
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'

DCN_kkbox:
    model: DCN
    dataset_id: kkbox_x1
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000  # 10000
    embedding_dim: 32
    dnn_hidden_units: [ 1024, 512,256 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 10
    shuffle: True
    seed: 20222023
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'